day=str(input())
if(day=='Sunday'):
  print('yes')
elif(day=='Monday'):
  print('no')
elif(day=='Tuesday'):
  print('no')
elif(day=='Wednesday'):
  print('no')
elif(day=='Thursday'):
  print('no')
elif(day=='Friday'):
  print('no')
elif(day=='Saturday'):
  print('no')
else:
  exit()
